/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

//PD8 - USART3_TX
//PD9 - USART3_RX

char Tab[5] = {'H', 'E', 'L', 'L', 'O'};

void BUTTON_CONF(void);
void Delay(void);
void UART3_CONF(void);
void PRINT_TAB(char Tab[]);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	BUTTON_CONF();
	UART3_CONF();

	while(1){
		Delay();
		Delay();
		Delay();
		Delay();
		PRINT_TAB(Tab);
	}
}

void BUTTON_CONF(void){
	//GPIO PORT C CLOCK ENABLE
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	//INPUT
	GPIOC->MODER &= ~(GPIO_MODER_MODER13);
	//NO PULL UP, NO PULL DOWN
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR13);
}

void Delay(void){
	uint32_t time;
	for(time = 0; time < 99999; time++){}
}

void UART3_CONF(void){
	//GPIO PORT C CLOCK ENABLE
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	//PD8 - USART3_TX (ALTERNATE FUNCTION)
	GPIOD -> MODER |= GPIO_MODER_MODER8_1;
	GPIOD -> AFR[1] |= 0x7;
	//PD9 - USART3_RX (ALTERNATE FUNCTION)
	GPIOD -> MODER |= GPIO_MODER_MODER9_1;
	GPIOD -> AFR[1] |= (0x7 << 4);
	//OPEN - DRAIN
	GPIOD -> OTYPER |= GPIO_OTYPER_OT9;

	//USART3 CLOCK ENABLE
	RCC -> APB1ENR |= RCC_APB1ENR_USART3EN;
	//BAUD RATE - 115200
	USART3 -> BRR = 16000000 / 115200;
	//FRAME 8N1
	//USART ENABLE
	USART3 -> CR1 |= USART_CR1_UE;
	//TRANSMITTER ENABLE
	USART3 -> CR1 |= USART_CR1_TE;
	//RECEIVER ENABLE
	USART3 -> CR1 |= USART_CR1_RE;
}

void PRINT_TAB(char Tab[]){
	while(!(USART3 -> ISR & USART_ISR_TXE)){  }
	for(uint8_t i = 0; i < 5; i++){
		//Tab[i] TO BUFFER
		USART3 -> TDR = Tab[i];
		while(!(USART3 -> ISR & USART_ISR_TXE)){  }
	}
	//ENTER -> NEW LINE
	USART3 -> TDR = 0x0D;
	while(!(USART3 -> ISR & USART_ISR_TXE)){  }
}
