/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

//PD8 - USART3_TX
//PD9 - USART3_RX

char Tab[5] = {'H', 'E', 'L', 'L', 'O'};

int main(void)
{

	BUTTON_CONF();
	UART3_CONF();
	UART3_TX_EN();

	while(1){
		Delay();
		Delay();
		Delay();
		Delay();
		PRINT_TAB(Tab);
	}
}
